version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=brainout
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d brainout -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  botti:
    build:
      context: ./bot-src
      dockerfile: DockerFile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BOT_TOKEN: 'TOKEN'
